/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CandidateRouteImport } from './routes/candidate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidateSettingsRouteImport } from './routes/candidate.settings'
import { Route as CandidateResumeRouteImport } from './routes/candidate.resume'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateNotificationsRouteImport } from './routes/candidate.notifications'
import { Route as CandidateMatchedJobsRouteImport } from './routes/candidate.matched-jobs'
import { Route as CandidateInterviewsRouteImport } from './routes/candidate.interviews'
import { Route as CandidateHelpRouteImport } from './routes/candidate.help'
import { Route as CandidateDashboardRouteImport } from './routes/candidate.dashboard'
import { Route as CandidateAppliedJobsRouteImport } from './routes/candidate.applied-jobs'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTriageRouteImport } from './routes/admin.triage'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResumesRouteImport } from './routes/admin.resumes'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminNotesRouteImport } from './routes/admin.notes'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminInterviewsRouteImport } from './routes/admin.interviews'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminAiAnalysisRouteImport } from './routes/admin.ai-analysis'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminJobsJobIdRouteImport } from './routes/admin.jobs.$jobId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRoute = CandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateSettingsRoute = CandidateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateResumeRoute = CandidateResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateNotificationsRoute = CandidateNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateMatchedJobsRoute = CandidateMatchedJobsRouteImport.update({
  id: '/matched-jobs',
  path: '/matched-jobs',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateInterviewsRoute = CandidateInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateHelpRoute = CandidateHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateAppliedJobsRoute = CandidateAppliedJobsRouteImport.update({
  id: '/applied-jobs',
  path: '/applied-jobs',
  getParentRoute: () => CandidateRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTriageRoute = AdminTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResumesRoute = AdminResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotesRoute = AdminNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInterviewsRoute = AdminInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiAnalysisRoute = AdminAiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsJobIdRoute = AdminJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AdminJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/candidate': typeof CandidateRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/ai-analysis': typeof AdminAiAnalysisRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/interviews': typeof AdminInterviewsRoute
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/resumes': typeof AdminResumesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/triage': typeof AdminTriageRoute
  '/admin/users': typeof AdminUsersRoute
  '/candidate/applied-jobs': typeof CandidateAppliedJobsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/help': typeof CandidateHelpRoute
  '/candidate/interviews': typeof CandidateInterviewsRoute
  '/candidate/matched-jobs': typeof CandidateMatchedJobsRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/resume': typeof CandidateResumeRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/candidate': typeof CandidateRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/ai-analysis': typeof AdminAiAnalysisRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/interviews': typeof AdminInterviewsRoute
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/resumes': typeof AdminResumesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/triage': typeof AdminTriageRoute
  '/admin/users': typeof AdminUsersRoute
  '/candidate/applied-jobs': typeof CandidateAppliedJobsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/help': typeof CandidateHelpRoute
  '/candidate/interviews': typeof CandidateInterviewsRoute
  '/candidate/matched-jobs': typeof CandidateMatchedJobsRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/resume': typeof CandidateResumeRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/candidate': typeof CandidateRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/ai-analysis': typeof AdminAiAnalysisRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/interviews': typeof AdminInterviewsRoute
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/resumes': typeof AdminResumesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/triage': typeof AdminTriageRoute
  '/admin/users': typeof AdminUsersRoute
  '/candidate/applied-jobs': typeof CandidateAppliedJobsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/help': typeof CandidateHelpRoute
  '/candidate/interviews': typeof CandidateInterviewsRoute
  '/candidate/matched-jobs': typeof CandidateMatchedJobsRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/resume': typeof CandidateResumeRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/candidate'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/reset-password'
    | '/signup'
    | '/admin/activity'
    | '/admin/ai-analysis'
    | '/admin/calendar'
    | '/admin/candidates'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/inbox'
    | '/admin/interviews'
    | '/admin/jobs'
    | '/admin/locations'
    | '/admin/notes'
    | '/admin/notifications'
    | '/admin/pipeline'
    | '/admin/reports'
    | '/admin/resumes'
    | '/admin/settings'
    | '/admin/triage'
    | '/admin/users'
    | '/candidate/applied-jobs'
    | '/candidate/dashboard'
    | '/candidate/help'
    | '/candidate/interviews'
    | '/candidate/matched-jobs'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/resume'
    | '/candidate/settings'
    | '/admin/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/candidate'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/reset-password'
    | '/signup'
    | '/admin/activity'
    | '/admin/ai-analysis'
    | '/admin/calendar'
    | '/admin/candidates'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/inbox'
    | '/admin/interviews'
    | '/admin/jobs'
    | '/admin/locations'
    | '/admin/notes'
    | '/admin/notifications'
    | '/admin/pipeline'
    | '/admin/reports'
    | '/admin/resumes'
    | '/admin/settings'
    | '/admin/triage'
    | '/admin/users'
    | '/candidate/applied-jobs'
    | '/candidate/dashboard'
    | '/candidate/help'
    | '/candidate/interviews'
    | '/candidate/matched-jobs'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/resume'
    | '/candidate/settings'
    | '/admin/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/candidate'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/reset-password'
    | '/signup'
    | '/admin/activity'
    | '/admin/ai-analysis'
    | '/admin/calendar'
    | '/admin/candidates'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/inbox'
    | '/admin/interviews'
    | '/admin/jobs'
    | '/admin/locations'
    | '/admin/notes'
    | '/admin/notifications'
    | '/admin/pipeline'
    | '/admin/reports'
    | '/admin/resumes'
    | '/admin/settings'
    | '/admin/triage'
    | '/admin/users'
    | '/candidate/applied-jobs'
    | '/candidate/dashboard'
    | '/candidate/help'
    | '/candidate/interviews'
    | '/candidate/matched-jobs'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/resume'
    | '/candidate/settings'
    | '/admin/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CandidateRoute: typeof CandidateRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate': {
      id: '/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/settings': {
      id: '/candidate/settings'
      path: '/settings'
      fullPath: '/candidate/settings'
      preLoaderRoute: typeof CandidateSettingsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/resume': {
      id: '/candidate/resume'
      path: '/resume'
      fullPath: '/candidate/resume'
      preLoaderRoute: typeof CandidateResumeRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/notifications': {
      id: '/candidate/notifications'
      path: '/notifications'
      fullPath: '/candidate/notifications'
      preLoaderRoute: typeof CandidateNotificationsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/matched-jobs': {
      id: '/candidate/matched-jobs'
      path: '/matched-jobs'
      fullPath: '/candidate/matched-jobs'
      preLoaderRoute: typeof CandidateMatchedJobsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/interviews': {
      id: '/candidate/interviews'
      path: '/interviews'
      fullPath: '/candidate/interviews'
      preLoaderRoute: typeof CandidateInterviewsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/help': {
      id: '/candidate/help'
      path: '/help'
      fullPath: '/candidate/help'
      preLoaderRoute: typeof CandidateHelpRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/applied-jobs': {
      id: '/candidate/applied-jobs'
      path: '/applied-jobs'
      fullPath: '/candidate/applied-jobs'
      preLoaderRoute: typeof CandidateAppliedJobsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/triage': {
      id: '/admin/triage'
      path: '/triage'
      fullPath: '/admin/triage'
      preLoaderRoute: typeof AdminTriageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resumes': {
      id: '/admin/resumes'
      path: '/resumes'
      fullPath: '/admin/resumes'
      preLoaderRoute: typeof AdminResumesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notes': {
      id: '/admin/notes'
      path: '/notes'
      fullPath: '/admin/notes'
      preLoaderRoute: typeof AdminNotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/interviews': {
      id: '/admin/interviews'
      path: '/interviews'
      fullPath: '/admin/interviews'
      preLoaderRoute: typeof AdminInterviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-analysis': {
      id: '/admin/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/admin/ai-analysis'
      preLoaderRoute: typeof AdminAiAnalysisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/$jobId': {
      id: '/admin/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/admin/jobs/$jobId'
      preLoaderRoute: typeof AdminJobsJobIdRouteImport
      parentRoute: typeof AdminJobsRoute
    }
  }
}

interface AdminJobsRouteChildren {
  AdminJobsJobIdRoute: typeof AdminJobsJobIdRoute
}

const AdminJobsRouteChildren: AdminJobsRouteChildren = {
  AdminJobsJobIdRoute: AdminJobsJobIdRoute,
}

const AdminJobsRouteWithChildren = AdminJobsRoute._addFileChildren(
  AdminJobsRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAiAnalysisRoute: typeof AdminAiAnalysisRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminInterviewsRoute: typeof AdminInterviewsRoute
  AdminJobsRoute: typeof AdminJobsRouteWithChildren
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminNotesRoute: typeof AdminNotesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResumesRoute: typeof AdminResumesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTriageRoute: typeof AdminTriageRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAiAnalysisRoute: AdminAiAnalysisRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminInterviewsRoute: AdminInterviewsRoute,
  AdminJobsRoute: AdminJobsRouteWithChildren,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminNotesRoute: AdminNotesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResumesRoute: AdminResumesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTriageRoute: AdminTriageRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CandidateRouteChildren {
  CandidateAppliedJobsRoute: typeof CandidateAppliedJobsRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  CandidateHelpRoute: typeof CandidateHelpRoute
  CandidateInterviewsRoute: typeof CandidateInterviewsRoute
  CandidateMatchedJobsRoute: typeof CandidateMatchedJobsRoute
  CandidateNotificationsRoute: typeof CandidateNotificationsRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateResumeRoute: typeof CandidateResumeRoute
  CandidateSettingsRoute: typeof CandidateSettingsRoute
}

const CandidateRouteChildren: CandidateRouteChildren = {
  CandidateAppliedJobsRoute: CandidateAppliedJobsRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  CandidateHelpRoute: CandidateHelpRoute,
  CandidateInterviewsRoute: CandidateInterviewsRoute,
  CandidateMatchedJobsRoute: CandidateMatchedJobsRoute,
  CandidateNotificationsRoute: CandidateNotificationsRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateResumeRoute: CandidateResumeRoute,
  CandidateSettingsRoute: CandidateSettingsRoute,
}

const CandidateRouteWithChildren = CandidateRoute._addFileChildren(
  CandidateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CandidateRoute: CandidateRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
